package enums;

public enum StudentComparatorsEnum {
    STUDENTFULLNAMECOMPARATOR,
    STUDENTUNIVERSITYIDCOMPARATOR,
    STUDENTCURRENTCOURSENUMBERCOMPARATOR,
    STUDENTAVGEXAMSCORECOMPARATOR;

    StudentComparatorsEnum() {
    }
}
