package enums;

public enum UniversityComparatorsEnum {
    UNIVERSITYIDCOMPARATOR,
    UNIVERSITYFULLNAMECOMPARATOR,
    UNIVERSITYSHORTNAMECOMPARATOR,
    UNIVERSITYYEAROFFOUNDATIONCOMPARATOR,
    UNIVERSITYSTUDYPROFILECOMPARATOR;

    UniversityComparatorsEnum() {
    }
}
